server:
  port: 8082
spring:
  application:
    name: DistributedTradeCacheApplication
  redis:
    password: 123456
    sentinel:
      master: mymaster
      nodes:
        - 172.27.107.50:26379
        - 172.27.107.50:26380
        - 172.27.107.50:26381
logging:
  config: classpath:logback-spring.xml