server:
  port: 8082
spring:
  application:
    name: DistributedTradeCacheApplication
  redis:
    password: ${REDIS_PWD}
    sentinel:
      master: mymaster
      nodes:
        - ${REDIS1_URL}
        - ${REDIS2_URL}
        - ${REDIS3_URL}
logging:
  config: classpath:logback-spring.xml
#swagger开关
swagger2:
  enable: true