server:
  port: 8082
spring:
  application:
    name: DistributedTradeCacheApplication
  redis:
    password: 123456
    sentinel:
      master: mymaster
      nodes:
        - 192.168.3.18:26379
        - 192.168.3.18:26380
        - 192.168.3.18:26381
logging:
  config: classpath:logback-spring.xml
#swagger开关
swagger2:
  enable: true